In [ ]:
import numpy as np

Arrays


In [ ]:
c=np.array([[[2,3,4],[5,6,7]],[[4,3,2],[7,6,5]]])
print(c)

[[[2 3 4]
  [5 6 7]]

 [[4 3 2]
  [7 6 5]]]


In [ ]:
A= np.array([2,4,45,6,7])
print(A)

[ 2  4 45  6  7]


In [ ]:
B= np.array([[2,3,4,5,6],[0,9,8,7,89]])
print(B)

[[ 2  3  4  5  6]
 [ 0  9  8  7 89]]


In [ ]:
C= np.array([[[2,3,4],[4,3,2]],[[5,6,7],[7,6,5]]])
print(C)

[[[2 3 4]
  [4 3 2]]

 [[5 6 7]
  [7 6 5]]]


In [ ]:
#checking dim
print(A.ndim)
print(B.ndim)
print(C.ndim)


1
2
3


In [ ]:
D= np.ones((3,2))
print(D)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
E=np.zeros((3,4))
print(E)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
F=np.eye(6,6)
print(F)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
j=np.eye(3,2)
print(j)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [ ]:
s=np.arange(4,21,3).reshape(2,3)
print(s)

[[ 4  7 10]
 [13 16 19]]


In [ ]:
s=np.arange(3,31,3)
print(s)

[ 3  6  9 12 15 18 21 24 27 30]


In [ ]:
s=np.arange(3,31,3).reshape(5,2)
print(s)

[[ 3  6]
 [ 9 12]
 [15 18]
 [21 24]
 [27 30]]


In [ ]:
k=np.arange(5,1001,5)
print(k)

[   5   10   15   20   25   30   35   40   45   50   55   60   65   70
   75   80   85   90   95  100  105  110  115  120  125  130  135  140
  145  150  155  160  165  170  175  180  185  190  195  200  205  210
  215  220  225  230  235  240  245  250  255  260  265  270  275  280
  285  290  295  300  305  310  315  320  325  330  335  340  345  350
  355  360  365  370  375  380  385  390  395  400  405  410  415  420
  425  430  435  440  445  450  455  460  465  470  475  480  485  490
  495  500  505  510  515  520  525  530  535  540  545  550  555  560
  565  570  575  580  585  590  595  600  605  610  615  620  625  630
  635  640  645  650  655  660  665  670  675  680  685  690  695  700
  705  710  715  720  725  730  735  740  745  750  755  760  765  770
  775  780  785  790  795  800  805  810  815  820  825  830  835  840
  845  850  855  860  865  870  875  880  885  890  895  900  905  910
  915  920  925  930  935  940  945  950  955  960  965  970  975  980
  985 

In [ ]:
V=np.linspace(25,50,10)
print(V)

[25.         27.77777778 30.55555556 33.33333333 36.11111111 38.88888889
 41.66666667 44.44444444 47.22222222 50.        ]


In [ ]:
L=np.arange(1,7).reshape(2,3)
print(L)
print("\n")
R=np.arange(9,15).reshape(2,3)
print(R)

[[1 2 3]
 [4 5 6]]


[[ 9 10 11]
 [12 13 14]]


In [ ]:
print(L+R)

[[10 12 14]
 [16 18 20]]


In [ ]:
G=np.sum((L,R))
print(G)

90


In [ ]:
L=np.arange(1,7).reshape(2,3)
print(L)
print("\n")
R=np.arange(9,15).reshape(2,3)
print(R)

[[1 2 3]
 [4 5 6]]


[[ 9 10 11]
 [12 13 14]]


In [ ]:
G=np.sum((L,R),axis=0)# adds rows
print(G)

[[10 12 14]
 [16 18 20]]


In [ ]:
G=np.sum((L,R),axis=1)#
print(G)

[[ 5  7  9]
 [21 23 25]]


In [ ]:
G=np.sum((L,R),axis=2)
print(G)

[[ 6 15]
 [30 39]]


In [ ]:
h=np.ones((4,2))
g=np.ones((4,2))
print(np.sum((h,g),axis=0))

[[2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]]


In [ ]:
b=np.array([25,289,361,81])
for i in b:
  print(np.sqrt(i), "square root of", i)

5.0 square root of 25
17.0 square root of 289
19.0 square root of 361
9.0 square root of 81


In [ ]:
a=np.array([34,35,36,37,38,39])
a.resize(2,3)
b=np.array([4,5,6,7,8,9])
b.resize(2,3)
print(a)
print("\n")
print(b)

[[34 35 36]
 [37 38 39]]


[[4 5 6]
 [7 8 9]]


In [ ]:
print(np.vstack((b, a)))
print("\n")
print(np.hstack((a, b)))

[[ 4  5  6]
 [ 7  8  9]
 [34 35 36]
 [37 38 39]]


[[34 35 36  4  5  6]
 [37 38 39  7  8  9]]


In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a)



[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
print(np.dstack(a))

[[[34 37]
  [35 38]
  [36 39]]]


In [ ]:
 pip install python-nmap


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 1.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for python-nmap: filename=python_nmap-0.7.1-py2.py3-none-any.whl size=20633 sha256=4793be49341d567b2ff95fac19fc9dd5d05d7219b265fcddb3f374ad23007745
  Stored in directory: /root/.cache/pip/wheels/da/bd/c6/0342ac886d4deb8d166a3191eb2566f738c5b1574cb0a8cd62
Successfully built python-nmap


In [ ]:
import nmap

def run_nmap_scan(target):
    # Initialize Nmap PortScanner object
    nm = nmap.PortScanner()

    # Perform a basic TCP SYN scan
    nm.scan(hosts=target, arguments='-sS')

    # Print scan results
    for host in nm.all_hosts():
        print(f'Host : {host} ({nm[host].hostname()})')
        print('State : %s' % nm[host].state())

        for proto in nm[host].all_protocols():
            print('----------')
            print(f'Protocol : {proto}')

            ports = nm[host][proto].keys()
            for port in ports:
                print(f'Port : {port}\tState : {nm[host][proto][port]["state"]}\tService : {nm[host][proto][port]["name"]}')

# Example usage
if __name__ == "__main__":
    target = '192.168.1.1'
    run_nmap_scan(target)


PortScannerError: 'nmap program was not found in path. PATH is : /opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/google-cloud-sdk/bin'

In [ ]:
!pip install python-nmap


In [ ]:
import nmap


In [ ]:
!nmap --version


/bin/bash: line 1: nmap: command not found


In [ ]:
# Define the target IP address
target = '192.168.1.1'

# Run the Nmap scan
run_nmap_scan(target)


PortScannerError: 'nmap program was not found in path. PATH is : /opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/google-cloud-sdk/bin'