In [ ]:
import numpy as np

In [ ]:
G=np.arange(0,32).reshape(8,4)
print(G)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [ ]:
A=np.random.rand(8,4) #rand - range between 0 and 1
print(A)

[[0.64144873 0.29301041 0.99783679 0.38491061]
 [0.58870043 0.68933277 0.95932735 0.97570331]
 [0.5180747  0.84404224 0.82495171 0.14071419]
 [0.27535277 0.62600909 0.868751   0.08269784]
 [0.67158046 0.79177011 0.10995747 0.23696013]
 [0.36790457 0.08940165 0.64602933 0.71052868]
 [0.55326073 0.05017365 0.92260411 0.30185048]
 [0.95589926 0.04678633 0.31373913 0.63813482]]


In [ ]:
A=10*np.random.rand(8,4) #rand - range between 0 and 1
print(A)

[[4.56394008 8.88277154 2.919284   3.49154793]
 [5.94974181 8.70355778 6.66646806 8.86700864]
 [1.44832843 8.14219599 0.39565832 3.05466844]
 [9.95937016 5.25428676 8.66194415 8.04713548]
 [4.82612781 6.8811304  7.60959875 1.49886469]
 [3.09429291 5.80042445 2.7715055  8.89231812]
 [8.96907937 4.28356942 4.83971937 0.59118486]
 [1.03440269 6.64440203 7.71980143 9.43831041]]


In [ ]:
A=np.floor(10*np.random.rand(8,4)) #rand - range between 0 and 1
print(A)

[[9. 7. 1. 5.]
 [5. 2. 4. 5.]
 [9. 6. 8. 8.]
 [9. 9. 4. 1.]
 [2. 1. 2. 3.]
 [7. 2. 3. 4.]
 [7. 2. 4. 8.]
 [2. 5. 6. 0.]]


In [ ]:
np.vsplit(A,4)

[array([[9., 7., 1., 5.],
        [5., 2., 4., 5.]]),
 array([[9., 6., 8., 8.],
        [9., 9., 4., 1.]]),
 array([[2., 1., 2., 3.],
        [7., 2., 3., 4.]]),
 array([[7., 2., 4., 8.],
        [2., 5., 6., 0.]])]

In [ ]:
np.vsplit(A,2)

[array([[9., 7., 1., 5.],
        [5., 2., 4., 5.],
        [9., 6., 8., 8.],
        [9., 9., 4., 1.]]),
 array([[2., 1., 2., 3.],
        [7., 2., 3., 4.],
        [7., 2., 4., 8.],
        [2., 5., 6., 0.]])]

In [ ]:
np.vsplit(A,(2,7))


[array([[9., 7., 1., 5.],
        [5., 2., 4., 5.]]),
 array([[9., 6., 8., 8.],
        [9., 9., 4., 1.],
        [2., 1., 2., 3.],
        [7., 2., 3., 4.],
        [7., 2., 4., 8.]]),
 array([[2., 5., 6., 0.]])]

In [ ]:
np.vsplit(A,(3,7))#split it after 3rd row 7th column

[array([[9., 7., 1., 5.],
        [5., 2., 4., 5.],
        [9., 6., 8., 8.]]),
 array([[9., 9., 4., 1.],
        [2., 1., 2., 3.],
        [7., 2., 3., 4.],
        [7., 2., 4., 8.]]),
 array([[2., 5., 6., 0.]])]

In [ ]:
np.vsplit(A,(4,8))

[array([[9., 7., 1., 5.],
        [5., 2., 4., 5.],
        [9., 6., 8., 8.],
        [9., 9., 4., 1.]]),
 array([[2., 1., 2., 3.],
        [7., 2., 3., 4.],
        [7., 2., 4., 8.],
        [2., 5., 6., 0.]]),
 array([], shape=(0, 4), dtype=float64)]

In [ ]:
np.hsplit(A,4)

[array([[9.],
        [5.],
        [9.],
        [9.],
        [2.],
        [7.],
        [7.],
        [2.]]),
 array([[7.],
        [2.],
        [6.],
        [9.],
        [1.],
        [2.],
        [2.],
        [5.]]),
 array([[1.],
        [4.],
        [8.],
        [4.],
        [2.],
        [3.],
        [4.],
        [6.]]),
 array([[5.],
        [5.],
        [8.],
        [1.],
        [3.],
        [4.],
        [8.],
        [0.]])]

In [ ]:
np.hsplit(A,(3,7))

[array([[9., 7., 1.],
        [5., 2., 4.],
        [9., 6., 8.],
        [9., 9., 4.],
        [2., 1., 2.],
        [7., 2., 3.],
        [7., 2., 4.],
        [2., 5., 6.]]),
 array([[5.],
        [5.],
        [8.],
        [1.],
        [3.],
        [4.],
        [8.],
        [0.]]),
 array([], shape=(8, 0), dtype=float64)]

In [ ]:
np.pi


3.141592653589793

In [ ]:
A= [np.pi/4,np.pi/3,np.pi/2,np.pi]
print(A)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
np.rad2deg(A)

array([ 45.,  60.,  90., 180.])

In [ ]:
np.deg2rad(A)

array([0.01370778, 0.01827705, 0.02741557, 0.05483114])

In [ ]:
np.sin(A)

array([7.07106781e-01, 8.66025404e-01, 1.00000000e+00, 1.22464680e-16])

In [ ]:
np.cos(1)

0.5403023058681398

In [ ]:
np.sin(1)

0.8414709848078965

In [ ]:
np.tan(np.pi/4)

0.9999999999999999


statistics


In [ ]:
st =np.array([23,45,67,89,21,34])

In [ ]:
np.mean(st)

46.5

In [ ]:
np.median(st)

39.5

In [ ]:
np.var(st)

597.9166666666666

In [ ]:
c= np.arange(1,5).reshape(2,2)

In [ ]:
np.linalg.inv(c)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
c=np.arange(1,25).reshape(6,4)
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
np.argmax(c)


23

In [ ]:
d=np.floor(10*np.random.rand(6,4))
print(d)

[[6. 1. 0. 4.]
 [2. 1. 3. 2.]
 [2. 7. 3. 0.]
 [9. 5. 4. 6.]
 [0. 4. 4. 4.]
 [0. 8. 6. 9.]]


In [ ]:
print(np.argmax(d))

12


In [ ]:
d=10*np.random.rand(6,4)
print(d)


[[7.21551845 0.44474068 2.50063271 5.32624358]
 [0.79205581 8.36862368 6.11720653 5.60982419]
 [5.42787206 9.07629956 8.8698149  5.39271196]
 [5.98628019 1.08439988 1.52132187 4.83148006]
 [5.49451542 6.93836166 1.6289139  8.67499575]
 [2.1956288  4.57257091 9.86504523 8.74112321]]


In [ ]:
print(np.argmax(d))

12


In [ ]:
print(np.argmax(c,axis =1))
print(c)

[3 3 3 3 3 3]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
print(np.argmax(c,axis =0))

[5 5 5 5]


In [ ]:
np.argmin(d)

1

In [ ]:
np.argmin(d,axis=0)

array([1, 0, 3, 3])

In [ ]:
np.argmin(d,axis=1)

array([1, 0, 3, 1, 2, 0])

searching

In [ ]:
a=np.array([34,56,7,17,88,91])
print(np.where(a%2==0))

(array([0, 1, 4]),)


In [ ]:
a=np.array([24,16,7,17,54,60])
print(np.where(a%6==0))

(array([0, 4, 5]),)


In [ ]:
b=np.array([6,7,8,9,10])
x=np.searchsorted(a,10)
print(x)

4


In [ ]:
print(np.sort(a))

[ 7 16 17 24 54 60]


In [ ]:
arr=np.array([True,False,True])
print(np.sort(arr))

[False  True  True]


In [ ]:
brr=np.array([[5,4,3],[9,8,7]])
print(np.sort(brr))

[[3 4 5]
 [7 8 9]]


In [ ]:
f=np.array([48,56,78,98,89])
filt=np.where(f%2==0)
print(filt)

(array([0, 1, 2, 3]),)


In [ ]:
f[filt]

array([48, 56, 78, 98])

In [ ]:
y

In [ ]:
names=np.array(['Jwalalitha','Sripadha','Siva Koti reddy'])
intials=np.array(['K','K','M'])
for i,j in zip(intials,names):
  print(i," . ",j)

K  .  Jwalalitha
K  .  Sripadha
M  .  Siva Koti reddy


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
print(np.multiply(a1,a2))

[ 200  420  660  920 1200 1500]


In [ ]:
print(np.divide(a1,a2))

[0.5        0.95238095 1.36363636 1.73913043 2.08333333 2.4       ]


In [ ]:
print(np.mod(a1,a2))

[10 20  8 17  2 10]


In [ ]:
print(np.divmod(a1,a2))

(array([0, 0, 1, 1, 2, 2]), array([10, 20,  8, 17,  2, 10]))


In [ ]:
a=1.2
print(a)
print(np.log2(a))


1.2
0.2630344058337938


In [ ]:
a=1.2
print(np.log(a))

0.1823215567939546


In [ ]:
print(np.log(a1))


[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301 4.09434456]


Other mathematical functions

In [ ]:
a2= np.array([5,6,7,10])
print(np.cumprod(a2))

[   5   30  210 2100]


In [ ]:
print(np.diff(a2))


[1 1 3]


In [ ]:
print(np.cumsum(a2))


[ 5 11 18 28]


In [ ]:
a=np.array